/* WIA3300-10 */

#define BOARD_PID		"WIA3300-10"
#define BOARD_NAME		"WIA3300-10"
#define BOARD_DESC		"WIA3300-10 Wireless Router"
#define BOARD_VENDOR_NAME	"WIA3300-10"
#define BOARD_VENDOR_URL	"http://www.mediatek.cn"
#define BOARD_MODEL_URL		"http://www.mediatek.cn"
#define BOARD_BOOT_TIME		30
#define BOARD_FLASH_TIME	45
#undef BOARD_GPIO_BTN_FN1
#define BOARD_GPIO_BTN_RESET 18
#undef BOARD_GPIO_BTN_WPS
#undef  BOARD_GPIO_LED_ALL
#undef  BOARD_GPIO_LED_WIFI
#define  BOARD_GPIO_LED_SW2G 4
#define  BOARD_GPIO_LED_SW5G 22
#define  BOARD_GPIO_LED_POWER	23
#define BOARD_GPIO_LED_LAN 24
#define BOARD_GPIO_LED_WAN	3
#undef BOARD_GPIO_LED_USB
#undef BOARD_GPIO_LED_ROUTER
#undef  BOARD_GPIO_PWR_USB
#define BOARD_HAS_5G_11AC	1
#define BOARD_NUM_ANT_5G_TX	2
#define BOARD_NUM_ANT_5G_RX	2
#define BOARD_NUM_ANT_2G_TX	2
#define BOARD_NUM_ANT_2G_RX	2
#define BOARD_NUM_ETH_LEDS	0
#define BOARD_HAS_EPHY_L1000	1
#define BOARD_HAS_EPHY_W1000	1
#define BOARD_NUM_UPHY_USB3	0
#define BOARD_USB_PORT_SWAP	0
